/* Replaces axpy's data.S (normally generated by script/gen_data.py and
 * assembled into the bare-metal image). Matches the RTL baseline's
 * args_app=4096 for _axpy (see ara/apps/run_rivec.sh). */
int n = 1024;
