
CC=/riscv/_install/bin/clang -std=c99
CXX=/riscv/_install/bin/clang++
# no FC for clang
FC=
flags = -O3 -fstrict-aliasing  -march=rv64gcv -menable-experimental-extensions -mabi=lp64d -mno-relax
vecflags = -mllvm -scalable-vectorization=on
noscalvecflags = -mllvm -scalable-vectorization=off 
novecflags = -fno-vectorize  -mllvm -scalable-vectorization=off
omp_flags=-fopenmp=libomp

ifdef VEC_REPORT
vecflags+=-Rpass=loop-vectorize -Rpass-missed=loop-vectorize -Rpass-analysis=loop-vectorize
#vecflags+=-mllvm -debug-only=loop-vectorize
#vecflags+=-Rpass-analysis=loop-vectorize
endif

# Print cycle count immediately at the end of each ROI (default: disabled)
# enable with: make RDCYCLE=1
ifdef RDCYCLE
flags += -DRDCYCLE
endif

ieee_math_flags+=
fast_math_flags+=-ffast-math

ifdef PRECISE_MATH
$(warning No 'precise' math flags for clang!)
endif

