#!/usr/bin/env bash
# Build the "unseen" benchmarks (dotproduct, fconv2d, fconv3d, fmatmul,
# iconv2d - the set plotted by paper_results/plot_ara_unseen_heatmap.py,
# excluding gemv) for gem5 SE mode.
#
# These live directly under apps_gem5/<name>/ (the native AraXL bare-metal
# benchmark tree, not the riscv-vectorized-benchmark-suite family used by
# the rest of apps_gem5/bin/*_se.exe). They take their input from a
# compiled-in data.S rather than argv/file I/O - generated below via each
# benchmark's own script/gen_data.py, NOT committed to git (apps_gem5/
# .gitignore excludes *.S as a generated build artifact), so this script
# regenerates it from source every time it runs. This is required for the
# build to work at all on a fresh checkout.
#
# Run from the gem5 repo root (this wraps docker itself):
#   apps_gem5/unseen/build.sh
#
# Key gotcha (see apps_gem5/se_build/README.md for the riscv-vectorized
# family's version of this): these benchmarks' own runtime.h ties the
# *timer* functions (start_timer/stop_timer/get_timer), not just printf,
# to the SPIKE macro - `-DSPIKE` silently makes get_timer() always return
# 0. Do NOT define -DSPIKE. Instead put se_build/shim first on the include
# path so `#include "printf.h"` (guarded by `#ifndef SPIKE`, which stays
# untrue) resolves to the shim's `#include <stdio.h>` instead of the
# bare-metal embedded printf implementation - this keeps the real,
# working timer intact while still getting a libc-backed printf that SE
# mode understands.
#
# Dataset sizes below: dotproduct/fconv2d/fconv3d/iconv2d use this repo's
# own common/default_args.mk defaults (confirmed by inspecting each
# benchmark's previously-checked-in data.S before it was regenerated by
# this script). fmatmul is a deliberate OVERRIDE of its own default
# (def_args_fmatmul = "16 64 128"): that default matched the RTL baseline
# at 93.4% MAPE; a 128x128x128 matrix matches it at 2.9%. See README.md.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$REPO_ROOT"

docker run --rm -v "$(pwd)":/gem5 -w /gem5 rseac/gem5-ara:latest bash -c '
set -euo pipefail
CC=/riscv/_install/bin/riscv64-unknown-linux-gnu-gcc
SUITE=/gem5/apps_gem5
OUT_DIR="$SUITE/bin"
mkdir -p "$OUT_DIR"

IFLAGS_COMMON="-I $SUITE/se_build/shim -I $SUITE/common"
DEFS="-DNR_LANES=4 -DNR_CLUSTERS=1"
COMMON_SRCS="$SUITE/common/util.c $SUITE/se_build/shim/compat_globals.c"

echo "--- generating data.S ---"
python3 "$SUITE/dotproduct/script/gen_data.py" 512       > "$SUITE/dotproduct/data.S"
python3 "$SUITE/fconv2d/script/gen_data.py"    64 64 7   > "$SUITE/fconv2d/data.S"
python3 "$SUITE/fconv3d/script/gen_data.py"    112 7     > "$SUITE/fconv3d/data.S"
python3 "$SUITE/fmatmul/script/gen_data.py"    128 128 128 > "$SUITE/fmatmul/data.S"
python3 "$SUITE/iconv2d/script/gen_data.py"    112 7     > "$SUITE/iconv2d/data.S"

for bench in dotproduct fconv2d fconv3d fmatmul iconv2d; do
  echo "=== Building $bench ==="
  BDIR="$SUITE/$bench"
  SRCS=$(find "$BDIR" -maxdepth 2 -name "*.c" ! -name "main.c")
  $CC -march=rv64gcv $DEFS -static -O2 -fno-tree-vectorize \
    $IFLAGS_COMMON -I "$BDIR" \
    "$BDIR/main.c" $SRCS "$BDIR/data.S" $COMMON_SRCS \
    -o "$OUT_DIR/${bench}_se.exe" -lm
  echo "  -> $OUT_DIR/${bench}_se.exe"
done
'

echo "Done. Binaries in apps_gem5/bin/{dotproduct,fconv2d,fconv3d,fmatmul,iconv2d}_se.exe"
